# Generate client constants and Windows metadata from release.json.
param(
    [Parameter(Mandatory=$true)][string]$ResourceCompiler
)
$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$release = Get-Content -LiteralPath (Join-Path $projectRoot 'release.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$version = [string]$release.version
$build = [int]$release.build
$fileVersion = [string]$release.file_version
if ($build -le 0 -or $version -cnotmatch '^[0-9a-z.-]+$') { throw 'Invalid release version or build.' }
if ($fileVersion -notmatch '^\d+\.\d+\.\d+\.\d+$') { throw 'File version must contain four integers.' }
$numbers = @($fileVersion.Split('.') | ForEach-Object { [int]$_ })
if (@($numbers | Where-Object { $_ -gt 65535 }).Count -ne 0) { throw 'File version component exceeds 65535.' }
$ResourceCompiler = (Resolve-Path -LiteralPath $ResourceCompiler).Path
$preprocessor = Join-Path (Split-Path -Parent $ResourceCompiler) 'cpp.exe'
if (-not (Test-Path -LiteralPath $preprocessor -PathType Leaf)) { throw 'cpp.exe must be beside windres.exe.' }

function Write-IfChanged([string]$Path, [string]$Content) {
    $Content = $Content.Replace("`r`n", "`n").TrimEnd("`r", "`n") + "`n"
    if (-not [IO.File]::Exists($Path) -or [IO.File]::ReadAllText($Path).Replace("`r`n", "`n") -cne $Content) {
        [IO.File]::WriteAllText($Path, $Content, [Text.UTF8Encoding]::new($false))
    }
}

$unitTemplate = @'
unit GameBuildInfo;
{$mode objfpc}{$H+}{$codepage UTF8}
{ Generated by tools/generate-release.ps1 from release.json. }
interface
const
  ClientVersion = '{0}';
  ClientBuild = {1};
  ClientCaption = 'REZVIVO {0}';
  ClientUserAgent = 'REZVIVO/{0}';
implementation
end.
'@
Write-IfChanged (Join-Path $projectRoot 'code/GameBuildInfo.pas') ($unitTemplate.Replace('{0}', $version).Replace('{1}', [string]$build))

$resource = Join-Path $projectRoot 'rezvivo-version.rc'
$resourceText = @"
MAINICON ICON "data/branding/rezvivo.ico"

1 VERSIONINFO
FILEVERSION $($numbers -join ',')
PRODUCTVERSION $($numbers -join ',')
FILEFLAGSMASK 0x3fL
FILEFLAGS 0x2L
FILEOS 0x40004L
FILETYPE 0x1L
BEGIN
 BLOCK "StringFileInfo"
 BEGIN
  BLOCK "040904b0"
  BEGIN
   VALUE "CompanyName", "REZVIVO\0"
   VALUE "FileDescription", "REZVIVO cycling simulator (alpha)\0"
   VALUE "FileVersion", "$fileVersion\0"
   VALUE "ProductVersion", "$version\0"
   VALUE "InternalName", "REZVIVO\0"
   VALUE "OriginalFilename", "REZVIVO.exe\0"
   VALUE "ProductName", "REZVIVO\0"
  END
 END
 BLOCK "VarFileInfo"
 BEGIN
  VALUE "Translation", 0x0409, 1200
 END
END
"@
Write-IfChanged $resource $resourceText
Push-Location $projectRoot
try {
    & $ResourceCompiler ("--preprocessor=" + $preprocessor) -i $resource -o (Join-Path $projectRoot 'rezvivo-version.res') -O res
    if ($LASTEXITCODE -ne 0) { throw "Resource compilation failed: $LASTEXITCODE" }
} finally { Pop-Location }
Write-Output "Client $version build $build"
