"""Generate client constants and Windows metadata from release.json."""
import json
from pathlib import Path
import subprocess
import sys
import shutil

root = Path(__file__).resolve().parents[1]
release = json.loads((root/'release.json').read_text(encoding='utf-8'))
version, build = release['version'], int(release['build'])
file_version = release['file_version']
assert build > 0 and all(c in '0123456789abcdefghijklmnopqrstuvwxyz.-' for c in version)
numbers = [int(x) for x in file_version.split('.')]
assert len(numbers) == 4 and all(0 <= x <= 65535 for x in numbers)

def write_if_changed(path, content):
    if not path.exists() or path.read_text(encoding='utf-8') != content:
        path.write_text(content, encoding='utf-8')

write_if_changed(root/'code/GameBuildInfo.pas', f'''unit GameBuildInfo;
{{$mode objfpc}}{{$H+}}{{$codepage UTF8}}
{{ Generated by tools/generate-release.py from release.json. }}
interface
const
  ClientVersion = '{version}';
  ClientBuild = {build};
  ClientCaption = 'REZVIVO {version}';
  ClientUserAgent = 'REZVIVO/{version}';
implementation
end.
''')
resource = root/'rezvivo-version.rc'
write_if_changed(resource, f'''MAINICON ICON "data/branding/rezvivo.ico"

1 VERSIONINFO
FILEVERSION {','.join(map(str, numbers))}
PRODUCTVERSION {','.join(map(str, numbers))}
FILEFLAGSMASK 0x3fL
FILEFLAGS 0x2L
FILEOS 0x40004L
FILETYPE 0x1L
BEGIN
 BLOCK "StringFileInfo"
 BEGIN
  BLOCK "040904b0"
  BEGIN
   VALUE "CompanyName", "REZVIVO\\0"
   VALUE "FileDescription", "REZVIVO cycling simulator (alpha)\\0"
   VALUE "FileVersion", "{file_version}\\0"
   VALUE "ProductVersion", "{version}\\0"
   VALUE "InternalName", "REZVIVO\\0"
   VALUE "OriginalFilename", "REZVIVO.exe\\0"
   VALUE "ProductName", "REZVIVO\\0"
  END
 END
 BLOCK "VarFileInfo"
 BEGIN
  VALUE "Translation", 0x0409, 1200
 END
END
''')
compiler = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(shutil.which('windres') or 'windres')
subprocess.run([str(compiler), '--preprocessor='+str(compiler.with_name('cpp.exe')), '-i', str(resource), '-o', str(root/'rezvivo-version.res'), '-O', 'res'], cwd=root, check=True)
print('Client', version, 'build', build)
