unit GameBuildInfo;
{$mode objfpc}{$H+}{$codepage UTF8}
{ Generated by tools/generate-release.ps1 from release.json. }
interface
const
  ClientVersion = '0.3.2-alpha.1';
  ClientBuild = 9;
  ClientCaption = 'REZVIVO 0.3.2-alpha.1';
  ClientUserAgent = 'REZVIVO/0.3.2-alpha.1';
implementation
end.
