{ AUTO-GENERATED PROGRAM FILE — manually edited for cross-platform builds.

  Builds on:
  - Windows (x86_64): full BLE stack — WinRT + Win32 GATT + SimpleBLE,
    plus ANT+ stub (Garmin USB stick, requires SDK).
  - Linux (x86_64) / macOS: SimpleBLE only.
  - Android: AndroidBLEProvider via CGE Android Java service.
  - iOS / Web: builds, no BLE provider yet.

  All transport-specific units are conditionally included so the
  project compiles cleanly on every CGE target. }

program third_person_navigation_standalone;

{$ifdef MSWINDOWS} {$apptype GUI} {$endif}

{ This adds icons and version info for Windows,
  automatically created by "castle-engine compile". }
{$ifdef CASTLE_AUTO_GENERATED_RESOURCES} {$R castle-auto-generated-resources.res} {$endif}
{$if defined(MSWINDOWS) and not defined(CASTLE_AUTO_GENERATED_RESOURCES)} {$R rezvivo-version.res} {$endif}

uses
  {$if defined(FPC) and (not defined(CASTLE_DISABLE_THREADS))}
    {$info Thread support enabled.}
    {$ifdef UNIX} CThreads, {$endif}
  {$endif}
  McpRelayBootstrap,
  Osm3dOSHeap,          // <-- ВОТ ЭТО (ставит ОС-менеджер в initialization)
  SysUtils,
  CastleAutoGenerated in 'castleautogenerated.pas',
  CastleWindow,

  { ── Cross-platform game code ── }
  GameEnemy in 'code/gameenemy.pas',
  GameMenuTile in 'code/GameMenuTile.pas',
  WorkoutFile in 'code/WorkoutFile.pas',
  WorkoutLibrary in 'code/WorkoutLibrary.pas',
  GameWorkoutPreview in 'code/GameWorkoutPreview.pas',
  GameViewMenu in 'code/gameviewmenu.pas',
  GameViewPlay in 'code/gameviewplay.pas',
  GameViewDevices  in 'code/GameViewDevices.pas',
  GameViewBikeFit  in 'code/GameViewBikeFit.pas',
  BikeGeometryLib  in '../Bikeparametric/BikeGeometryLib.pas',
  GameViewFreeRide in 'code/GameViewFreeRide.pas',
  GameViewTraining in 'code/GameViewTraining.pas',
  GameViewWorkoutEditor in 'code/GameViewWorkoutEditor.pas',
  GameViewProfile  in 'code/GameViewProfile.pas',
  GameViewEvents   in 'code/GameViewEvents.pas',
  GameInitialize in 'code/gameinitialize.pas',
  GameCrashReports in 'code/GameCrashReports.pas',
  FTMSProtocol in 'code/FTMSProtocol.pas',
  GameDeviceTypes in 'code/GameDeviceTypes.pas',
  DebugLog in 'code/DebugLog.pas',
  AppSettings in 'code/AppSettings.pas',
  GameProfiler in 'code/GameProfiler.pas',
  GameTransportBase in 'code/GameTransportBase.pas',
  GameDeviceManager in 'code/GameDeviceManager.pas',
  GameDeviceService in 'code/GameDeviceService.pas',
  TrainerData in 'code/TrainerData.pas',
  GameRemoteRiders in 'code/GameRemoteRiders.pas',
  GameBLEHud in 'code/GameBLEHud.pas',
  GameCameraControl in 'code/GameCameraControl.pas',
  GameOsmStreaming in 'code/GameOsmStreaming.pas',

  { ── Cross-platform desktop BLE (SimpleBLE C wrapper) ── }
  {$if defined(MSWINDOWS) or defined(LINUX) or defined(DARWIN)}
  SimpleBle in 'code/simpleble.pas',
  SimpleBLEProvider in 'code/SimpleBLEProvider.pas',
  {$ifend}

  { ── Windows-only transports ── }
  {$ifdef MSWINDOWS}
  WinBluetoothLE in 'code/WinBluetoothLE.pas',
  BLEDevice in 'code/BLEDevice.pas',
  BLEManager in 'code/BLEManager.pas',
  WinRTBLEProvider in 'code/WinRTBLEProvider.pas',
  ANTPlus in 'code/ANTPlus.pas',
  ANTPlusLibusb0 in 'code/ANTPlusLibusb0.pas',
  {$endif}

  { ── Android-only transport (BLE via CGE Android Java service) ── }
  {$ifdef ANDROID}
  AndroidBLEProvider in 'code/AndroidBLEProvider.pas',
  {$endif}

  { ── Bike & rider geometry (cross-platform, pure CGE/X3D) ── }
  BikeParametric in '../BikeParametric/BikeParametric.pas',
  BikeParametric_Frame in '../BikeParametric/BikeParametric_Frame.pas',
  BikeParametric_Fork in '../BikeParametric/BikeParametric_Fork.pas',
  BikeParametric_DropBar in '../BikeParametric/BikeParametric_DropBar.pas',
  BikeParametric_FlatBar in '../BikeParametric/BikeParametric_FlatBar.pas',
  BikeParametric_Seat in '../BikeParametric/BikeParametric_Seat.pas',
  BikeParametric_Wheel in '../BikeParametric/BikeParametric_Wheel.pas',
  BikeParametric_Crankset in '../BikeParametric/BikeParametric_Crankset.pas',
  BikeParametric_Drivetrain in '../BikeParametric/BikeParametric_Drivetrain.pas',
  BikeParametric_Animation in '../BikeParametric/BikeParametric_Animation.pas',
  BikeJSON in '../BikeParametric/BikeJSON.pas',
  RiderBuildThread in '../BikeParametric/RiderBuildThread.pas',
  GameBikeAvatar in 'code/GameBikeAvatar.pas';

{ Forces using a dedicated (faster) GPU on laptops with multiple GPUs.
  See https://castle-engine.io/dedicated_gpu }
{$if (not defined(CASTLE_NO_FORCE_DEDICATED_GPU)) and
     (defined(CPU386) or defined(CPUX64) or defined(CPUAMD64)) and
     (defined(MSWINDOWS) or (defined(LINUX) and defined(FPC)))
}
    {$ifdef FPC}
      {$asmmode intel}
    {$endif}

    procedure NvOptimusEnablement; {$ifdef FPC}assembler; nostackframe;{$endif}
    asm
      {$ifdef CPU64}
      {$ifndef FPC}
      .NOFRAME
      {$endif}
      {$endif}
      dd 1
    end;

    procedure AmdPowerXpressRequestHighPerformance; {$ifdef FPC}assembler; nostackframe;{$endif}
    asm
      {$ifdef CPU64}
      {$ifndef FPC}
      .NOFRAME
      {$endif}
      {$endif}
      dd 1
    end;

    exports
      NvOptimusEnablement,
      AmdPowerXpressRequestHighPerformance;
{$ifend}

begin
  StartCrashReports;
  try
    Application.MainWindow.OpenAndRun;
    MarkClientCleanExit;
  except
    on E:SysUtils.Exception do begin CaptureCrash(E);raise;end;
  end;
end.
